// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commentuseriDinttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentuseriDinttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "202004060434510_comment-useriD-int-to-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
